baseURL = "https://example.com"
languageCode = "en-us"
title = "Living Life"
theme = "bare"
enableGitInfo = true

[taxonomies]
  tag = "tags"
  series = "series"

[params]
mainSections = ["post"]
author = "Paul Applegate"
email = "me@paulapplegate.com"
repoLink = "https://github.com/orf/bare-hugo-theme"
description = 'Living life and writing some things down along the way'
# PostCSS is harder than it should be to get working on a theme
# example site. It's easy on _your_ site.
postcss = false
# Include the author name in the <title> of articles
includeAuthorInTitle = true

[[params.social]]
icon = "github"
url = "https://github.com/theapplegates"
